language: cpp

matrix:
  include:
    - dist: bionic
      addons:
        apt:
          packages:
            - g++-7
            - libdbus-1-dev
            - libpulse-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: bionic
      addons:
        apt:
          packages:
            - clang-7.0
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - eval "${MATRIX_EVAL}"

script:
  - make
      

