language: cpp

matrix:
  include:
    - dist: bionic
      addons:
        apt:
          packages:
            - g++-7
            - libdbus-1-dev
            - libpulse-dev
            - meson
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - dist: bionic
      addons:
        apt:
          update: true
          packages:
            - clang-9
            - libdbus-1-dev
            - libpulse-dev
            - meson
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++99"

before_script:
  - mkdir build && meson setup build && cd build
  - eval "${MATRIX_EVAL}"

script:
- gcc -v && g++ -v && cmake --version
- meson compile