language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - dist: bionic
      addons:
        apt:
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
  apt:
    update: true
    packages:
      - libdbus-1-dev
      - libpulse-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - eval "${MATRIX_EVAL}"
      

